version: "3.0"

services:
  server:
    build: ./
    restart: unless-stopped
    environment:
      - PORT=3000
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - SECRET=s3cret # change me
    ports:
      - 3000:3000
    volumes:
      - ./src/proxies.json:/app/proxies.json